### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by bufgix** [KeyLo99/God#1]
i installed dependencies but 
![image](https://user-images.githubusercontent.com/22038798/58595384-241c5100-8279-11e9-8533-a3f523e866f1.png)

**Comment by orhun** [comment]
This problem is probably about the terminal library and this issue should be at that repository. Also found a issue that includes same error: https://github.com/carmark/pseudo-terminal-go/issues/4

And if you ask me, it's expected that `god` tool will have problems with the other operating systems. First reason for that is commands which are responsible for parsing. [#L86](https://github.com/KeyLo99/God/blob/master/god.go#L86) I don't know much about the Windows side of this commands but probably I'll test the tool on Windows after releasing the first version. Oh, it's a `Linux utility` for a reason.
